### ISSUE TITLE
Outdated document content

### ISSUE THREAD

**Issue by CharmNight** [MattBroach/DjangoRestMultipleModels#44]
https://django-rest-multiple-models.readthedocs.io/en/latest/flat-options.html

```
from drf_multiple_model.views import FlatMultipleModelAPIView

class TextAPIView(FlatMultipleModelAPIView):
    querylist = [
        {
            'querylist': Play.objects.all(),
            'serializer_class': PlaySerializer,
            'label': 'drama',
        },
        {
            'querylist': Poem.objects.filter(style='Sonnet'),
            'serializer_class': PoemSerializer,
            'label': 'sonnet'
        },
        ....
    ]
```
When I follow the above, I get an error  ['All items in the MyDemoAPI querylist attribute should contain a `queryset` key']

**Comment by rlabrecque** [comment]
https://github.com/MattBroach/DjangoRestMultipleModels/pull/43

**Comment by MattBroach** [comment]
Just confirming that yes, as @rlabrecque pointed out, this is an error the documentation.  If you instead use `queryset` instead of `querylist` inside each dict object, it should work as intended.  The documentation has been updated to correct this error, and sorry for the confusion.
